# import libarary

In [14]:
from sklearn.svm import SVC
from PIL import Image
import numpy as np
from sklearn.metrics import accuracy_score
import tensorflow as tf
#from keras.layers import *
from tensorflow.keras import *
from tensorflow.keras.layers import *
from tensorflow.keras.preprocessing.image import array_to_img, img_to_array, load_img
import np_utils
from tensorflow.keras.utils import to_categorical
from tensorflow import lite
#from keras.models import Sequential

# Function(Convert to tflite)

In [7]:
def save_model(h5_path, model_path):
   
    
    model = Sequential()
    model.add(Conv2D(20, kernel_size = 5, padding="same", input_shape=data_x[0].shape))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
    model.add(Conv2D(50, kernel_size = 5, padding="same"))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
    model.add(Flatten())
    model.add(Dense(500))
    model.add(Activation("relu"))
    model.add(Dense(26))
    model.add(Activation("softmax"))

    model.compile(loss = "categorical_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    model.fit(data_x, data_y, epochs=10, batch_size=130)


    
    # 케라스 모델과 변수 모두 저장
    model.save(h5_path)

    # -------------------------------------- #

    # 저장한 파일로부터 모델 변환 후 다시 저장
    converter = tf.lite.TFLiteConverter.from_keras_model_file(h5_path)
    flat_data = converter.convert()

    with open(model_path, 'wb') as f:
        f.write(flat_data)


# Image processing test

# Make dataset

In [3]:
word={'a':0,'b':1,'c':2,'d':3,'e':4,'f':5,'g':6,'h':7,'i':8,'j':9,'k':10,'l':11,'m':12,'n':13,'o':14,'p':15,'q':16,'r':17,'s':18,'t':19,'u':20,'v':21,'w':22,'x':23,'y':24,'z':25}

## color

In [4]:
data_x=[]
data_y=[]
test_x=[]
test_y=[]
cnt=0
cnt1=0
cnt2=0
cnt3=0
for j in range(0,100):
    for i in ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']:
        #print(i+str(j)+".JPG")
        #temp=Image.open(i+str(j)+".jpg")
        try:
            temp=Image.open("cnn-spectrogram\\"+i+"\\"+i+str(j)+".JPG")
        except:
            cnt+=1
            continue
        temp=temp.resize((235,145))
        temp_np=np.array(temp)
        
        #temp_np=temp_np.reshape(-1)
        if j in range(90,100):
            cnt1+=1
            test_x.append(temp_np)
            test_y.append(word[i])
        
        else:
            data_x.append(temp_np)
            data_y.append(word[i])
            
for j in range(0,100):
    for i in ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']:
        #print(i+str(j)+".JPG")
        #temp=Image.open(i+str(j)+".jpg")
        try:
            temp=Image.open("cnn-spectrogram2\\"+i+"\\"+i+str(j)+".JPG")
        except:
            cnt+=1
            continue
        temp=temp.resize((235,145))
        temp_np=np.array(temp)
        
      
        #temp_np=temp_np.reshape(-1)
        if j in range(90,100):
            cnt2+=1
            test_x.append(temp_np)
            test_y.append(word[i])
        
        else:
            data_x.append(temp_np)
            data_y.append(word[i])

for j in range(0,100):
    for i in ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']:
        #print(i+str(j)+".JPG")
        #temp=Image.open(i+str(j)+".jpg")
        try:
            temp=Image.open("cnn-spectrogram3\\"+i+"\\"+i+str(j)+".JPG")
        except:
            cnt+=1
            continue
        temp=temp.resize((235,145))
        temp_np=np.array(temp)
        
      
        #temp_np=temp_np.reshape(-1)
        if j in range(90,100):
            cnt3+=1
            test_x.append(temp_np)
            test_y.append(word[i])
        
        else:
            data_x.append(temp_np)
            data_y.append(word[i])
        
        
       
            
test_x=np.array(test_x)
test_y=np.array(test_y)
data_x=np.array(data_x)
data_y=np.array(data_y)

#normalization
data_x = data_x.astype('float32')/255
test_x = test_x.astype('float32')/255

test_y = to_categorical(test_y,num_classes=26)
data_y = to_categorical(data_y,num_classes=26)
print(cnt)

853


In [5]:
data_x.shape

(6249, 145, 235, 3)

In [6]:
test_x.shape

(698, 145, 235, 3)

In [7]:
2600*2-853

4347

In [8]:
3909+438

4347

In [6]:
print(cnt1,cnt2,cnt3)

260 178 260


In [28]:
print(cnt1,cnt2,cnt3)

260 178 2600


In [25]:
438-178

260

In [31]:
data_x[0]

array([[[0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        ...,
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355]],

       [[0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        ...,
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355]],

       [[0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        ...,
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355],
        [0.23921569, 0.14901961, 0.65882355]],

       ...,

       [[0.23921569, 0.14901961, 0.6666667 ],
        [0.23921569, 0.14901961, 0.6666667 ],
        [0.23921569, 0

## gray scale

In [154]:
data_x=[]
data_y=[]
test_x=[]
test_y=[]
for i in ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']:
    for j in range(1,6):
        #print(i+str(j)+".JPG")
        temp=Image.open("data\\"+i+str(j)+".JPG")
        temp=temp.resize((90,30))
        temp=temp.convert('L') #흑백여부
        
        temp_np=np.array(temp)
        #temp_np = temp_np.reshape((1,)+temp_np.shape)
        temp_np=temp_np.reshape(30,90,1)
        if(j==5):
            test_x.append(temp_np)
            test_y.append(word[i])
        else:
            data_x.append(temp_np)
            data_y.append(word[i])
            
test_x=np.array(test_x)
test_y=np.array(test_y)
data_x=np.array(data_x)
data_y=np.array(data_y)


test_y = to_categorical(test_y,num_classes=26)
data_y = to_categorical(data_y,num_classes=26)

-----------------------------

In [14]:
data_x.shape

(130, 145, 235, 3)

In [15]:
test_x.shape

(26, 145, 235, 3)

In [33]:
test_y[0]

'a'

In [207]:
data_x[0].shape

(70, 235, 3)

In [213]:
data_y.shape

(104,)

In [218]:
len(word)

26

# Train CNN

## Build model

### LeNet5

In [219]:
model=Sequential()
model.add(Conv2D(6, kernel_size=(5,5), strides=1,  activation='tanh', input_shape=data_x[0].shape, padding='same')) #C1
model.add(AveragePooling2D(pool_size=(2,2))) #S2
model.add(Conv2D(16, kernel_size=(5,5), strides=1, activation='tanh', padding='valid')) #C3
model.add(AveragePooling2D(pool_size=(2,2))) #S4
model.add(Flatten()) #Flatten
model.add(Dense(120, activation='tanh')) #C5
model.add(Dense(84, activation='tanh')) #F6
model.add(Dense(len(word), activation='softmax')) #Output layer



model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])

### LeNet5 -2 

In [9]:
model = Sequential()
model.add(Conv2D(20, kernel_size = 5, padding="same", input_shape=data_x[0].shape))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
model.add(Conv2D(50, kernel_size = 5, padding="same"))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
model.add(Flatten())
model.add(Dense(500))
model.add(Activation("relu"))
model.add(Dense(26))
model.add(Activation("softmax"))

model.compile(loss = "categorical_crossentropy", optimizer='adam', metrics=["accuracy"])

### test model

In [197]:
model = Sequential()
model.add(Conv2D(64, kernel_size=(3,3), padding='same',
                input_shape=(data_x.shape[1], data_x.shape[2], data_x.shape[3]), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(128, kernel_size=(3,3),padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(256, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(26, activation='softmax'))


model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

## fit

In [10]:
history = model.fit(data_x, data_y, 
                    epochs=10, batch_size=26)

Train on 6249 samples
Epoch 1/10
6249/6249 [==============================] - 352s 56ms/sample - loss: 2.0206 - accuracy: 0.4759
Epoch 2/10
6249/6249 [==============================] - 353s 57ms/sample - loss: 0.4930 - accuracy: 0.8648
Epoch 3/10
6249/6249 [==============================] - 354s 57ms/sample - loss: 0.1550 - accuracy: 0.9602
Epoch 4/10
6249/6249 [==============================] - 356s 57ms/sample - loss: 0.0787 - accuracy: 0.9778
Epoch 5/10
6249/6249 [==============================] - 356s 57ms/sample - loss: 0.0583 - accuracy: 0.9832
Epoch 6/10
6249/6249 [==============================] - 366s 59ms/sample - loss: 0.0306 - accuracy: 0.9907
Epoch 7/10
6249/6249 [==============================] - 372s 59ms/sample - loss: 0.0160 - accuracy: 0.9963
Epoch 8/10
6249/6249 [==============================] - 365s 58ms/sample - loss: 0.0224 - accuracy: 0.9933
Epoch 9/10
6249/6249 [==============================] - 361s 58ms/sample - loss: 0.0404 - accuracy: 0.9918
Epoch 10/10
624

## get score

### color

In [32]:
result = model.predict_classes(test_x)

In [13]:


test_y_label = []
for y in test_y:
    test_y_label.append(np.argmax(y))

accuracy_score(test_y_label, result)

0.836676217765043

In [ ]:
accuracy_score(test_y_label, result)

In [23]:
test_x[0].shape

(145, 235, 3)

In [26]:
test_x[0].reshape(1,235,145,3).shape

(1, 235, 145, 3)

In [35]:
result

array([ 3,  1,  2,  3,  4,  5,  6,  7,  8,  9, 16, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0, 21, 22, 23, 13, 25,  3,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 16, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0, 21, 22, 23, 13,
       25, 13,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19,  0, 21, 22, 23, 24, 25, 13,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0, 21, 22, 23,
       24, 25, 13,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 13,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25,  6,  1,  2,  3,  4,  5,  6,  7,  8, 18, 10, 11, 12, 13,
       14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,  6,  1,  2,  3,  4,
        5,  6,  7,  8, 18, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25,  6,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17

In [12]:
for i in enumerate(test_y_label):
    if i[1]!=result[i[0]]:
        print("[",i[0],'] real:',list(word.keys())[i[1]],'| predict:',list(word.keys())[result[i[0]]])

[ 0 ] real: a | predict: b
[ 9 ] real: j | predict: l
[ 20 ] real: u | predict: w
[ 24 ] real: y | predict: g
[ 26 ] real: a | predict: b
[ 46 ] real: u | predict: w
[ 50 ] real: y | predict: g
[ 52 ] real: a | predict: b
[ 72 ] real: u | predict: w
[ 76 ] real: y | predict: g
[ 78 ] real: a | predict: b
[ 98 ] real: u | predict: w
[ 102 ] real: y | predict: g
[ 104 ] real: a | predict: b
[ 124 ] real: u | predict: w
[ 128 ] real: y | predict: g
[ 130 ] real: a | predict: b
[ 150 ] real: u | predict: w
[ 154 ] real: y | predict: g
[ 156 ] real: a | predict: g
[ 176 ] real: u | predict: w
[ 180 ] real: y | predict: g
[ 182 ] real: a | predict: g
[ 202 ] real: u | predict: w
[ 206 ] real: y | predict: g
[ 208 ] real: a | predict: g
[ 228 ] real: u | predict: w
[ 234 ] real: a | predict: g
[ 243 ] real: j | predict: i
[ 254 ] real: u | predict: w
[ 260 ] real: d | predict: o
[ 262 ] real: h | predict: i
[ 263 ] real: l | predict: r
[ 267 ] real: s | predict: g
[ 271 ] real: x | predict: t

In [16]:
result1=0
result2=0
result3=0

for i in enumerate(test_y_label):
    if i[1]!=result[i[0]]:
        if(i[0] in range(0,260)):
            result1+=1
        elif(i[0] in range(260,438)):
            result2+=1
        elif(i[0] in range (438,698)):
            result3+=1
            
result1=((cnt1-result1)/cnt1)*100
result2=((cnt2-result2)/cnt2)*100
result3=((cnt3-result3)/cnt3)*100

print(result1,result2,result3)

88.46153846153845 76.96629213483146 63.84615384615384


In [29]:

test_y_label = []
for y in test_y:
    test_y_label.append(np.argmax(y))

accuracy_score(test_y_label, result)

0.20408163265306123

In [30]:
for i in enumerate(test_y_label):
    if i[1]!=result[i[0]]:
        print("[",i[0],'] real:',list(word.keys())[i[1]],'| predict:',list(word.keys())[result[i[0]]])

[ 0 ] real: a | predict: d
[ 7 ] real: h | predict: b
[ 20 ] real: u | predict: a
[ 24 ] real: y | predict: n
[ 26 ] real: a | predict: d
[ 33 ] real: h | predict: b
[ 46 ] real: u | predict: a
[ 50 ] real: y | predict: n
[ 52 ] real: a | predict: d
[ 72 ] real: u | predict: a
[ 76 ] real: y | predict: n
[ 78 ] real: a | predict: d
[ 98 ] real: u | predict: a
[ 102 ] real: y | predict: n
[ 104 ] real: a | predict: d
[ 128 ] real: y | predict: n
[ 130 ] real: a | predict: g
[ 156 ] real: a | predict: g
[ 182 ] real: a | predict: g
[ 208 ] real: a | predict: g
[ 234 ] real: a | predict: g
[ 260 ] real: d | predict: o
[ 262 ] real: h | predict: j
[ 263 ] real: l | predict: s
[ 264 ] real: m | predict: y
[ 273 ] real: a | predict: d
[ 274 ] real: d | predict: o
[ 276 ] real: h | predict: j
[ 278 ] real: m | predict: y
[ 280 ] real: p | predict: k
[ 288 ] real: a | predict: d
[ 289 ] real: c | predict: e
[ 290 ] real: d | predict: o
[ 292 ] real: h | predict: j
[ 294 ] real: m | predict: y


[ 726 ] real: c | predict: b
[ 727 ] real: d | predict: f
[ 728 ] real: e | predict: z
[ 729 ] real: f | predict: j
[ 730 ] real: g | predict: v
[ 731 ] real: h | predict: v
[ 732 ] real: i | predict: j
[ 734 ] real: k | predict: w
[ 735 ] real: l | predict: v
[ 736 ] real: m | predict: j
[ 737 ] real: n | predict: j
[ 738 ] real: o | predict: c
[ 739 ] real: p | predict: v
[ 740 ] real: q | predict: j
[ 741 ] real: r | predict: w
[ 742 ] real: s | predict: f
[ 743 ] real: t | predict: y
[ 744 ] real: u | predict: j
[ 745 ] real: v | predict: b
[ 746 ] real: w | predict: j
[ 747 ] real: x | predict: j
[ 748 ] real: y | predict: u
[ 749 ] real: z | predict: b
[ 750 ] real: a | predict: j
[ 751 ] real: b | predict: f
[ 752 ] real: c | predict: b
[ 753 ] real: d | predict: f
[ 754 ] real: e | predict: d
[ 755 ] real: f | predict: j
[ 756 ] real: g | predict: h
[ 757 ] real: h | predict: v
[ 758 ] real: i | predict: j
[ 760 ] real: k | predict: w
[ 761 ] real: l | predict: g
[ 762 ] real: 

[ 1247 ] real: d | predict: j
[ 1248 ] real: e | predict: c
[ 1249 ] real: f | predict: v
[ 1251 ] real: h | predict: r
[ 1252 ] real: i | predict: j
[ 1254 ] real: k | predict: j
[ 1255 ] real: l | predict: g
[ 1256 ] real: m | predict: j
[ 1257 ] real: n | predict: u
[ 1258 ] real: o | predict: j
[ 1259 ] real: p | predict: v
[ 1260 ] real: q | predict: j
[ 1261 ] real: r | predict: w
[ 1262 ] real: s | predict: j
[ 1263 ] real: t | predict: y
[ 1264 ] real: u | predict: j
[ 1265 ] real: v | predict: b
[ 1266 ] real: w | predict: v
[ 1267 ] real: x | predict: j
[ 1268 ] real: y | predict: j
[ 1269 ] real: z | predict: v
[ 1270 ] real: a | predict: z
[ 1271 ] real: b | predict: f
[ 1273 ] real: d | predict: j
[ 1274 ] real: e | predict: c
[ 1275 ] real: f | predict: v
[ 1277 ] real: h | predict: r
[ 1278 ] real: i | predict: j
[ 1279 ] real: j | predict: g
[ 1280 ] real: k | predict: w
[ 1281 ] real: l | predict: g
[ 1282 ] real: m | predict: j
[ 1283 ] real: n | predict: u
[ 1284 ] r

[ 1575 ] real: t | predict: y
[ 1576 ] real: u | predict: j
[ 1578 ] real: w | predict: j
[ 1579 ] real: x | predict: j
[ 1580 ] real: y | predict: w
[ 1581 ] real: z | predict: b
[ 1582 ] real: a | predict: w
[ 1583 ] real: b | predict: f
[ 1584 ] real: c | predict: a
[ 1585 ] real: d | predict: f
[ 1586 ] real: e | predict: f
[ 1587 ] real: f | predict: j
[ 1588 ] real: g | predict: z
[ 1589 ] real: h | predict: v
[ 1592 ] real: k | predict: c
[ 1593 ] real: l | predict: g
[ 1594 ] real: m | predict: u
[ 1595 ] real: n | predict: w
[ 1596 ] real: o | predict: c
[ 1597 ] real: p | predict: v
[ 1598 ] real: q | predict: j
[ 1599 ] real: r | predict: j
[ 1600 ] real: s | predict: j
[ 1601 ] real: t | predict: y
[ 1602 ] real: u | predict: j
[ 1604 ] real: w | predict: j
[ 1605 ] real: x | predict: j
[ 1606 ] real: y | predict: w
[ 1607 ] real: z | predict: b
[ 1608 ] real: a | predict: w
[ 1609 ] real: b | predict: f
[ 1611 ] real: d | predict: f
[ 1612 ] real: e | predict: f
[ 1614 ] r

[ 2311 ] real: b | predict: f
[ 2312 ] real: c | predict: e
[ 2313 ] real: d | predict: j
[ 2314 ] real: e | predict: j
[ 2315 ] real: f | predict: v
[ 2316 ] real: g | predict: j
[ 2317 ] real: h | predict: v
[ 2318 ] real: i | predict: j
[ 2320 ] real: k | predict: f
[ 2321 ] real: l | predict: y
[ 2322 ] real: m | predict: j
[ 2323 ] real: n | predict: j
[ 2324 ] real: o | predict: c
[ 2325 ] real: p | predict: j
[ 2326 ] real: q | predict: w
[ 2327 ] real: r | predict: j
[ 2328 ] real: s | predict: v
[ 2329 ] real: t | predict: g
[ 2330 ] real: u | predict: v
[ 2332 ] real: w | predict: b
[ 2333 ] real: x | predict: j
[ 2334 ] real: y | predict: u
[ 2335 ] real: z | predict: j
[ 2336 ] real: a | predict: w
[ 2337 ] real: b | predict: f
[ 2338 ] real: c | predict: e
[ 2339 ] real: d | predict: j
[ 2340 ] real: e | predict: j
[ 2341 ] real: f | predict: v
[ 2342 ] real: g | predict: j
[ 2343 ] real: h | predict: v
[ 2344 ] real: i | predict: j
[ 2346 ] real: k | predict: f
[ 2347 ] r

[ 2630 ] real: i | predict: j
[ 2631 ] real: j | predict: e
[ 2632 ] real: k | predict: f
[ 2633 ] real: l | predict: e
[ 2634 ] real: m | predict: j
[ 2635 ] real: n | predict: j
[ 2636 ] real: o | predict: c
[ 2637 ] real: p | predict: v
[ 2638 ] real: q | predict: f
[ 2639 ] real: r | predict: j
[ 2640 ] real: s | predict: e
[ 2641 ] real: t | predict: j
[ 2642 ] real: u | predict: j
[ 2644 ] real: w | predict: b
[ 2645 ] real: x | predict: j
[ 2646 ] real: y | predict: b
[ 2647 ] real: z | predict: j
[ 2648 ] real: a | predict: d
[ 2649 ] real: b | predict: w
[ 2650 ] real: c | predict: e
[ 2651 ] real: d | predict: f
[ 2652 ] real: e | predict: j
[ 2653 ] real: f | predict: v
[ 2654 ] real: g | predict: j
[ 2655 ] real: h | predict: v
[ 2656 ] real: i | predict: j
[ 2657 ] real: j | predict: v
[ 2658 ] real: k | predict: f
[ 2659 ] real: l | predict: e
[ 2660 ] real: m | predict: j
[ 2661 ] real: n | predict: w
[ 2662 ] real: o | predict: c
[ 2663 ] real: p | predict: v
[ 2664 ] r

[ 2984 ] real: y | predict: w
[ 2986 ] real: a | predict: f
[ 2987 ] real: b | predict: f
[ 2989 ] real: d | predict: c
[ 2990 ] real: e | predict: g
[ 2991 ] real: f | predict: j
[ 2992 ] real: g | predict: b
[ 2993 ] real: h | predict: v
[ 2994 ] real: i | predict: v
[ 2996 ] real: k | predict: v
[ 2997 ] real: l | predict: g
[ 2998 ] real: m | predict: y
[ 2999 ] real: n | predict: j
[ 3000 ] real: o | predict: c
[ 3001 ] real: p | predict: i
[ 3002 ] real: q | predict: a
[ 3003 ] real: r | predict: j
[ 3004 ] real: s | predict: e
[ 3005 ] real: t | predict: v
[ 3006 ] real: u | predict: j
[ 3008 ] real: w | predict: b
[ 3009 ] real: x | predict: j
[ 3010 ] real: y | predict: w
[ 3012 ] real: a | predict: f
[ 3013 ] real: b | predict: f
[ 3015 ] real: d | predict: c
[ 3016 ] real: e | predict: g
[ 3017 ] real: f | predict: j
[ 3018 ] real: g | predict: b
[ 3019 ] real: h | predict: v
[ 3020 ] real: i | predict: e
[ 3022 ] real: k | predict: v
[ 3023 ] real: l | predict: g
[ 3024 ] r

In [32]:
result1=0
result2=0
result3=0

for i in enumerate(test_y_label):
    if i[1]!=result[i[0]]:
        if(i[0] in range(0,260)):
            result1+=1
        elif(i[0] in range(260,438)):
            result2+=1
        elif(i[0] in range (438,3038)):
            result3+=1
            
result1=((cnt1-result1)/cnt1)*100
result2=((cnt2-result2)/cnt2)*100
result3=((cnt3-result3)/cnt3)*100

print(result1,result2,result3)

91.92307692307692 78.08988764044943 9.307692307692307


In [39]:
test_img=Image.open("cnn-spectrogram\\"+"m"+"\\"+"m11"+".JPG") 
test_img=test_img.resize((235,145))
test_img=np.array(test_img)
test_img=test_img.astype('float32')/255

In [44]:
test_img.shape

(145, 235, 3)

In [58]:
test_img[70][80]

array([0.08627451, 0.67058825, 0.9372549 ], dtype=float32)

In [59]:
test_img[80][70]

array([0.10196079, 0.654902  , 0.7647059 ], dtype=float32)

In [41]:
result = model.predict_classes(test_img.reshape(1,145,235,3))

In [46]:
result_arr=model.predict(test_img.reshape(1,145,235,3))

In [42]:
result

array([12], dtype=int64)

In [60]:
result_arr

array([[1.2315868e-18, 1.5400330e-16, 4.1935730e-27, 2.5063741e-17,
        8.7193296e-30, 1.3292985e-17, 1.0092332e-12, 1.7364516e-14,
        8.7549433e-11, 1.3086886e-11, 3.3557019e-14, 3.7713731e-28,
        9.9999964e-01, 2.3270023e-12, 8.7233485e-24, 9.0331680e-14,
        9.5820379e-13, 5.2379693e-13, 8.9404217e-21, 4.2451462e-10,
        1.2145283e-13, 3.9992052e-17, 1.1197191e-09, 5.6708900e-14,
        7.8683954e-08, 2.5380362e-07]], dtype=float32)

In [54]:
max=0
max_idx=0
for idx,i in enumerate(result_arr[0]):
    #print(i)
    if(i>max):
        max=i
        max_idx=idx
print(max,max_idx)

0.99999964 12


# Convert to tflite

In [18]:
h5_path='./model/lenet5.h5'
model_path='./model/lenet5.tflite'


model.save(h5_path)

model2 = tf.keras.models.load_model(h5_path)
converter = tf.lite.TFLiteConverter.from_keras_model(model2)

#converter = lite.TFLiteConverter.from_keras_model_file(h5_path)
#tf.lite.TFLiteConverter.from_keras_model_file(h5_path)
flat_data = converter.convert()

with open(model_path, 'wb') as f:
    f.write(flat_data)


