# import libarary

In [2]:
from sklearn.svm import SVC
from PIL import Image
import numpy as np
from sklearn.metrics import accuracy_score

# Image processing test

In [30]:
"""
test=Image.open("a1.JPG")
test_np=np.array(test)
print(test_np.shape)
test_re=test.resize((256,256))
test_re_np=np.array(test_re)
print(test_re_np.shape)
"""


(146, 238, 3)
(256, 256, 3)


# Make dataset

In [4]:
word={'a':0,'b':1,'c':2,'d':3,'e':4,'f':5,'g':6,'h':7,'i':8,'j':9,'k':10,'l':11,'m':12,'n':13,'o':14,'p':15,'q':16,'r':17,'s':18,'t':19,'u':20,'v':21,'w':22,'x':23,'y':24,'z':25}

In [50]:

"""
data_x=[]
data_y=[]
test_x=[]
test_y=[]
for i in ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']:
    for j in range(1,6):
        #print(i+str(j)+".JPG")
        temp=Image.open(i+str(j)+".JPG")
        temp=temp.convert('L')
        temp=temp.resize((256,256))
        temp_np=np.array(temp)
        temp_np=temp_np.reshape(-1)
        if(j==5):
            test_x.append(temp_np)
            test_y.append(i)
        else:
            data_x.append(temp_np)
            data_y.append(i)
    """        

In [5]:
data_x=[]
data_y=[]
test_x=[]
test_y=[]
for j in range(1,7):
    for i in ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']:
        #print(i+str(j)+".JPG")
        temp=Image.open(i+str(j)+".jpg")
        
        #temp=Image.open("data\\"+i+str(j)+".JPG")
        #temp=temp.convert('L')
        temp=temp.resize((235,145))
        #temp=temp.resize((235,70))
        temp_np=np.array(temp)
        
        #temp_np=temp_np.reshape(-1)
        if(j==6):
            test_x.append(temp_np)
            test_y.append(word[i])
        else:
            data_x.append(temp_np)
            data_y.append(word[i])
            
test_x=np.array(test_x)
test_y=np.array(test_y)
data_x=np.array(data_x)
data_y=np.array(data_y)

#normalization
data_x = data_x.astype('float32')/255
test_x = test_x.astype('float32')/255

#test_y = to_categorical(test_y,num_classes=26)
#data_y = to_categorical(data_y,num_classes=26)

data_x= data_x.reshape(data_x.shape[0],-1)
test_x= test_x.reshape(test_x.shape[0],-1)

In [34]:
test_y[0]

0

In [35]:
data_y[0]

0

# Train SVM

In [24]:
svc = SVC(kernel='linear',gamma='auto')
svc.fit(data_x,data_y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

# Test

In [25]:
pred_y=svc.predict(test_x)

In [27]:
accuracy_score(test_y,pred_y)

0.07692307692307693

In [28]:
test_y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [29]:
pred_y

array([ 3,  1,  5, 22,  2,  3, 13,  3, 13, 12, 13,  2,  3,  5,  2, 13, 13,
       22,  2, 22, 22, 13, 22,  9,  2, 13])

In [12]:
for i in enumerate(test_y):
    if i[1]==pred_y[i[0]]:
        print(list(word.keys())[i[1]])
print("--------------------------------")
for i in enumerate(test_y):
    print('real:',list(word.keys())[i[1]],'| predict:',list(word.keys())[pred_y[i[0]]])

b
--------------------------------
real: a | predict: b
real: b | predict: b
real: c | predict: f
real: d | predict: b
real: e | predict: c
real: f | predict: b
real: g | predict: n
real: h | predict: c
real: i | predict: n
real: j | predict: b
real: k | predict: r
real: l | predict: c
real: m | predict: d
real: n | predict: f
real: o | predict: c
real: p | predict: r
real: q | predict: n
real: r | predict: w
real: s | predict: b
real: t | predict: b
real: u | predict: b
real: v | predict: n
real: w | predict: b
real: x | predict: j
real: y | predict: c
real: z | predict: b


In [39]:
pred_y=svc.predict(test_x)
accuracy_score(test_y,pred_y)

0.2692307692307692

In [40]:
test_y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [41]:
pred_y

array([ 0,  0,  2, 11,  2, 24,  3, 21,  8, 11, 15,  2, 10,  3, 14, 15, 16,
       17, 20, 11, 12, 17,  8,  8, 17, 21])

In [44]:
for i in enumerate(test_y):
    if i[1]==pred_y[i[0]]:
        print(list(word.keys())[i[1]])

a
c
i
o
p
q
r


In [45]:
for i in enumerate(test_y):
    print('real:',list(word.keys())[i[1]],'| predict:',list(word.keys())[pred_y[i[0]]])

real: a | predict: a
real: b | predict: a
real: c | predict: c
real: d | predict: l
real: e | predict: c
real: f | predict: y
real: g | predict: d
real: h | predict: v
real: i | predict: i
real: j | predict: l
real: k | predict: p
real: l | predict: c
real: m | predict: k
real: n | predict: d
real: o | predict: o
real: p | predict: p
real: q | predict: q
real: r | predict: r
real: s | predict: u
real: t | predict: l
real: u | predict: m
real: v | predict: r
real: w | predict: i
real: x | predict: i
real: y | predict: r
real: z | predict: v


## 흑백변환

In [53]:
accuracy_score(test_y,pred_y)

0.23076923076923078

In [55]:
pred_y

array(['o', 'a', 'c', 'o', 'c', 'y', 'p', 'v', 'i', 'j', 'f', 'e', 'h',
       'd', 'o', 'k', 'q', 'r', 'o', 'n', 'e', 'o', 'i', 'i', 'i', 'u'],
      dtype='<U1')